#!/usr/bin/env python3
"""
double_poisson_fit.py

Description:
This script calculates the inter-event wait times from tracked ion permeation 
events and fits the resulting distribution to a double-Poisson kinetic model.
This model captures the characteristic entry lag observed in the α7-nAChR pore.

Mathematical Model:
The probability density function (PDF) for the wait times (t) is defined as:
f(t) = n0 * [(\lambda_lag * \lambda_cond) / (\lambda_cond - \lambda_lag)] * (e^{-\lambda_lag * t} - e^{-\lambda_cond * t})

Inputs:
- Ion tracking data generated by `calc_ion_flux.py` (contains Start/End frames).
- Time step (dt) per frame to convert frames to nanoseconds.

Outputs:
- Prints the fitted parameters: Lag Rate (\lambda_lag) and Conduction Rate (\lambda_cond).
- Saves a plot of the wait time histogram overlaid with the fitted double-Poisson curve.
"""

import argparse
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit
import os

def double_poisson_pdf(t, llag, lcond, n0):
    """
    Double-Poisson Probability Density Function (PDF).
    Captures a two-step process (Unready -> Ready -> Conducted) yielding an entry lag.
    """
    # Prevent division by zero if parameters converge to the same value
    if np.isclose(lcond, llag):
        return np.zeros_like(t)
        
    amplitude = n0 * (llag * lcond) / (lcond - llag)
    return amplitude * (np.exp(-llag * t) - np.exp(-lcond * t))

def main():
    # 1. Setup Argument Parsing
    parser = argparse.ArgumentParser(description="Fit permeation wait times to a Double-Poisson model")
    parser.add_argument("--input", required=True, help="Path to the IonTracking.txt file from flux analysis")
    parser.add_argument("--dt", type=float, default=0.1, help="Time per frame in nanoseconds (default: 0.1 ns)")
    parser.add_argument("--bins", type=int, default=30, help="Number of histogram bins (default: 30)")
    parser.add_argument("--out_prefix", required=True, help="Prefix for saving the output plot")
    args = parser.parse_args()

    print(f"Loading event data from {args.input}...")
    
    if not os.path.exists(args.input):
        print(f"Error: Could not find {args.input}")
        return

    # 2. Extract Event Times
    # The flux script saves data as: [Ion_idx, Direction, Start_Frame, End_Frame]
    event_data = np.loadtxt(args.input)
    
    if len(event_data) < 3:
        print("Error: Not enough events to perform a statistical fit (minimum 3 required).")
        return

    # Extract start frames and sort them chronologically
    start_frames = np.sort(event_data[:, 2])
    
    # Calculate Wait Times (Inter-arrival times between consecutive events)
    wait_frames = np.diff(start_frames)
    wait_times_ns = wait_frames * args.dt

    print(f"Calculated {len(wait_times_ns)} wait times. Mean wait: {np.mean(wait_times_ns):.2f} ns.")

    # 3. Create Histogram for Fitting
    # Extract bin centers and counts to pass into scipy's curve_fit
    counts, bin_edges = np.histogram(wait_times_ns, bins=args.bins, density=False)
    bin_centers = (bin_edges[:-1] + bin_edges[1:]) / 2

    # 4. Perform Curve Fitting
    print("Fitting data to Double-Poisson model...")
    
    # Initial parameter guesses: [llag, lcond, n0]
    # We assume lcond is fast (short time) and llag is slow (long time) based on the Mathematica notebook
    initial_guess = [1/0.65, 1/3.84, np.max(counts)]
    
    # Set bounds to ensure rates remain positive
    bounds = (0, np.inf)

    try:
        popt, pcov = curve_fit(
            double_poisson_pdf, 
            bin_centers, 
            counts, 
            p0=initial_guess, 
            bounds=bounds,
            maxfev=10000
        )
        llag_fit, lcond_fit, n0_fit = popt
        
        print("\n--- Fit Results ---")
        print(f"Lag Rate (λ_lag):       {llag_fit:.4f} ns^-1")
        print(f"Conduction Rate (λ_cond): {lcond_fit:.4f} ns^-1")
        print(f"Amplitude scalar (n0):    {n0_fit:.4f}\n")
        
    except RuntimeError:
        print("Error: Curve fitting failed to converge. Try adjusting the bin size or initial guesses.")
        return

    # 5. Generate and Save Plot
    plt.figure(figsize=(8, 6))
    
    # Plot empirical histogram
    plt.bar(bin_centers, counts, width=(bin_edges[1]-bin_edges[0])*0.9, 
            alpha=0.6, color='skyblue', label='Empirical Wait Times')
    
    # Plot fitted curve
    t_smooth = np.linspace(0, np.max(wait_times_ns), 200)
    fit_curve = double_poisson_pdf(t_smooth, *popt)
    
    plt.plot(t_smooth, fit_curve, 'r-', lw=2, 
             label=f'Double-Poisson Fit\n$\lambda_{{lag}}$={llag_fit:.2f}, $\lambda_{{cond}}$={lcond_fit:.2f}')
    
    plt.title('Kinetics of Ion Permeation: Double-Poisson Fit')
    plt.xlabel('Wait Time (ns)')
    plt.ylabel('Frequency')
    plt.legend()
    plt.tight_layout()

    # Save plot
    out_plot = f"{args.out_prefix}_kinetic_fit.png"
    plt.savefig(out_plot, dpi=300)
    print(f"Kinetic fit plot successfully saved to {out_plot}")

if __name__ == "__main__":
    main()